apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync.gitlab: ""
  name: pact-broker-func
spec:
  destination:
    namespace: mxinfo-infrastructure
    server: https://kubernetes.default.svc
  project: default
  source:
  - repoURL: git@github.com:dmaxim/shared-infrastructure.git
    path: application-manifests/pact-func/pact-func
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      releaseName: pact-broker-func
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}

