apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync.gitlab: ""
  name: pact-broker
spec:
  destination:
    namespace: mxinfo-infrastructure
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: pact-broker/pact-broker
    helm:
    repoURL: https://pact-foundation.github.io/pact-broker-chart/
    targetRevision: 2.112.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}



