apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: monitoring
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      containers:
      - name: fluentd
        #image: fluent/fluentd-kubernetes-daemonset:v1.17.0-debian-elasticsearch8-1.5
        #image: fluent/fluentd-kubernetes-daemonset:v1.15-debian-elasticsearch7-1
        image: mxinfo.azurecr.io/fluentd-eventhub:0.1.0
        env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: FLUENT_ELASTICSEARCH_HOST
            value: "mxinfo-elastic-es-http.elastic-system.svc.cluster.local"
          - name: FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "https"
          - name: FLUENT_UID
            value: "0"
          - name: FLUENT_ELASTICSEARCH_RELOAD_CONNECTIONS
            value: "false"
          - name: FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX
            value: "mxinfo-logs"
          - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
            value: "/var/log/containers/fluentd*"
          - name: FLUENT_ELASTICSEARCH_USER
            value: "elastic"
          - name: FLUENT_ELASTICSEARCH_PASSWORD
            value: "<password>"
          - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
            value: "false"
          - name: AZURE_EVENT_HUBS_CONNECTION_STRING
            value: "<connection-string>"
          - name: AZURE_EVENT_HUBS_HUB_NAME
            value: "mxinfo-log-logging"
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
        - name: config-volume
          mountPath: /fluentd/etc/kubernetes.conf
          subPath: kubernetes.conf
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config-volume
        configMap:
          name: fluentd-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
