apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo-status
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: cluster-infrastructure
  source:
    path: cluster-infrastructure/manifests
    repoURL: https://github.com/dmaxim/shared-infrastructure.git
    targetRevision: main
