apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-params
spec:
  entrypoint: print-message
  serviceAccountName: argo-workflow-sa
  arguments:
    parameters:
    - name: message
      value: hello world

  templates:
  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["echo {{inputs.parameters.message}}"]