apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

resources:
  - resources/namespace.yaml
  - resources/cert-issuer.yaml
#  patches:
#    - path: patches/argocd-notifications-cm.yaml
