# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   annotations:
#     notifications.argoproj.io/subscribe.on-sync.gitlab: ""
#   name: app-with-secret
# spec:
#   destination:
#     namespace: default
#     server: https://kubernetes.default.svc
#   project: default
#   source:
#     path: testing/app-with-secret/manifests
#     repoURL: https://github.com/dmaxim/shared-infrastructure.git
#     targetRevision: main
#   syncPolicy:
#     automated: {}
