apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: wf-steps-template-parallel
spec:
  entrypoint: steps-template-parallel
  templates:
  - name: steps-template-parallel
    steps:
    - - name: step1
        template: task-template
    - - name: step2
        template: task-template
      - name: step3
        template: task-template
    - - name: step4
        template: task-template
  - name: task-template
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        print("task executed")