apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-sync.gitlab: ""
  name: monitoring-stack
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    path: monitoring/manifests
    repoURL: https://github.com/dmaxim/shared-infrastructure.git
    targetRevision: main
  syncPolicy:
    automated: {}
