apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
type: Opaque
data:
  runner-registration-token: <registration-token-base64>
  runner-token: <registration-token-base64>