apiVersion: v1
kind: Secret
metadata:
  name: gitlab-runner
  namespace: gitlab-runner
type: Opaque
data:
  runner-registration-token: <base64 encoded runner token>
  runner-token: <base64 encoded runner token>


