apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pact-broker-secrets
  namespace: pact-broker-poc
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: pact-broker-read
    secretKey: pact-broker-read
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: pact-broker-write
    secretKey: pact-broker-write
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: pact-broker-read-password
    secretKey: pact-broker-read-password
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: pact-broker-write-password
    secretKey: pact-broker-write-password
  refreshInterval: 30m
  secretStoreRef:
    kind: SecretStore
    name: pact-broker-secret-store
#   target:
#     creationPolicy: Owner
#     deletionPolicy: Retain
#     name: admin-portal-provisioning-workflow-secrets
# \