apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: pact-broker-secret-store
  namespace: pact-broker-poc

spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      environmentType: PublicCloud
      serviceAccountRef:
        name: pact-broker
      tenantId: 38ec304a-0fad-408b-b7cd-e04a2e25b885
      vaultUrl: <key vault url>
