apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: mxinfo-apm
  namespace: elastic-system
spec:
  version: 8.15.0
  count: 1
  elasticsearchRef:
    name: mxinfo-elastic
  kibanaRef:
    name: mxinfo-kibana