---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-role
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - pods/log
    - pods/exec
    - services
    - configmaps
    - secrets
  verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete
- apiGroups:
    - argoproj.io
  resources:
    - workflows
    - workflowtemplates
    - workflowtemplates/finalizers
    - workflowtasksets
    - workflowtasksets/finalizers
    - workflowtaskresults
    - cronworkflows
    - eventsources
    - sensors
  verbs:
    - create
    - get
    - list
    - watch
    - update
    - patch
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-rolebinding
subjects:
- kind: ServiceAccount
  name: argo-workflow-sa
roleRef:
  kind: Role
  name: argo-workflow-role
  apiGroup: rbac.authorization.k8s.io