apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v3.0.12
  #- github.com/argoproj/argo-workflows/manifests/cluster-install?ref=v3.6.0
  - resources/namespace.yaml
  #- resources/ingress.yaml
  #- resources/demo-app-one.yaml
  #- resources/sealed-secrets.yaml
  #- resources/app-with-secret.yaml

patches:
  - path: patches/argocd-cm.yaml
  - path: patches/argocd-server-deployment.yaml
  - path: patches/argocd-repo-server-deployment.yaml
  - path: patches/argocd-application-controller-statefulset.yaml
 # - path: patches/argocd-rbac-cm.yaml
