apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.slack: |
    token: $slack-token
  template.custom-slack-template: |
    message: |
      Application {{.app.metadata.name}} sync is {{.app.status.sync.status}}.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
  defaultTriggers: |
    - on-sync-status-unkown

  defaultTriggers.mattermost: |
    - on-sync-running
    - on-sync-succeeded
