apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - resources/namespace.yaml
  - resources/argocd-metrics.yaml
  - resources/argocd-repo.yaml
  - resources/argocd-server.yaml
